### ISSUE TITLE
NO idea how the config works

### ISSUE THREAD

**Issue by tankirules** [PhaserArray/TeamJoinerEnhanced#2]
Where is the option to give permissions? Is the permission to give in the friendly permissions tag or what?

**Comment by PhaserArray** [comment]
If you're upgrading from an older version, make sure to delete the old config first and let the default config generate. It should look something like this:

![Default Config Screenshot](https://cdn.discordapp.com/attachments/469965104213917698/675998851211198484/unknown.png)

There you add whatever permission you want to give to `GivenPermissionGroupId` and all the other perms members of that group could have as friendly permissions.

**Comment by tankirules** [comment]
yea whoops lul you fixed it for me in discord thanks bby
